name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest  # 或 ubuntu-latest/macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'  # 使用支持的Python版本

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # 安装requirements.txt中的所有依赖
        pip install pyinstaller  # 安装打包工具

    - name: Build executable
      run: |
        pyinstaller --onefile --name "ImageResizer" --hidden-import=tkinterdnd2 main.py

    - name: Upload release asset
      uses: softprops/action-gh-release@v2
      with:
        files: dist/ImageResizer.exe
    
