name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install Pillow==10.1.0
        pip install tkinterdnd2==0.3.0
        pip install pyinstaller

    - name: Copy tkdnd library from project
      run: |
        # 仅从项目本地复制，不执行任何下载操作
        New-Item -Path "C:\hostedtoolcache\windows\Python\3.8.10\x64\tcl\tkdnd2.9.2" -ItemType Directory -Force
        Copy-Item -Path "tkdnd\tkdnd2.9.2\*" -Destination "C:\hostedtoolcache\windows\Python\3.8.10\x64\tcl\tkdnd2.9.2" -Recurse -Force

    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --windowed src/main.py --icon=icon.ico --name=pyresize `
          --hidden-import=tkinterdnd2 `
          --add-data "tkdnd\tkdnd2.9.2;tkdnd2.9.2"

    - name: Upload release asset
      uses: softprops/action-gh-release@v2
      with:
        files: dist/三七改图.exe
