name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install Pillow==10.1.0
        pip install tkinterdnd2==0.3.0
        pip install pyinstaller

    - name: Download tkdnd library
      run: |
        # 使用更简单的方式下载tkdnd库
        Invoke-WebRequest -Uri "https://downloads.sourceforge.net/project/tkdnd/tkdnd/2.9.2/tkdnd-2.9.2-windows-x86_64.zip" -OutFile "tkdnd.zip"
        Expand-Archive -Path "tkdnd.zip" -DestinationPath "tkdnd" -Force

    - name: Build with PyInstaller
      run: |
        # 复制tkdnd库到Tcl目录
        Copy-Item -Path "tkdnd/tkdnd2.9.2/*" -Destination "C:/hostedtoolcache/windows/Python/3.8.10/x64/tcl/tkdnd2.9.2" -Recurse -Force
        
        # 打包应用程序
        pyinstaller --onefile --windowed src/main.py --icon=icon.ico --name=pyresize --hidden-import=tkinterdnd2

    - name: Upload release asset
      uses: softprops/action-gh-release@v2
      with:
        files: dist/pyresize.exe
