name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # 安装包含tkdnd的完整包
        pip install Pillow==10.1.0
        pip install tkdnd==0.2.0  # 这个包包含预编译的tkdnd库
        pip install pyinstaller

    - name: Build with PyInstaller
      run: |
        # 获取tkdnd库的安装路径
        python -c "import tkdnd; print('tkdnd installed at:', tkdnd.__path__[0])" > tkdnd_path.txt
        set /p TKDND_PATH=<tkdnd_path.txt
        
        # 打包应用程序，包含tkdnd库
        pyinstaller --onefile --windowed src/main.py --icon=icon.ico --name=pyresize `
          --hidden-import=tkinterdnd2 `
          --add-data "%TKDND_PATH%\lib;tkdnd"

    - name: Upload release asset
      uses: softprops/action-gh-release@v2
      with:
        files: dist/pyresize.exe
